### ISSUE TITLE
Magician's Toolset needs further definitions

### ISSUE THREAD

**Issue by woggy** [woggy/HekaCraft#3]
The Magician's Workbench is currently made using a pesheskef, scribe's palette and (vanilla) bowl.  This is not the final recipe, nor is the entirety of the toolset implemented.

**Comment by wolfwine** [comment]
pwW
kTc
b_s

p = pesheskef
w = white wool
W = wand (hekacraft.tool.baseWand)
k = knife
T = sun table
c = sugar cane
b = bowl
s = scribe's palette
